"""Contract test: Ensure .env.example stays in sync with the CLI generator.

This test guards against drift between the checked-in .env.example artifact
and the template generated by `minerva init`. If this test fails, run:

    uv run minerva init --force

Then commit the updated .env.example file.
"""

from pathlib import Path

from src.cli.commands.init import _render_env_example_template


def test_env_example_matches_generator():
    """Assert checked-in .env.example matches the CLI generator output exactly."""
    # Get the template content from the generator
    template_content = _render_env_example_template()

    # Read the checked-in .env.example file
    env_example_path = Path(".env.example")
    assert env_example_path.exists(), "Missing .env.example file"

    checked_in_content = env_example_path.read_text()

    # Compare content (ignoring only trailing newlines at end of file)
    template_normalized = template_content.rstrip("\n")
    checked_in_normalized = checked_in_content.rstrip("\n")

    if template_normalized != checked_in_normalized:
        # Calculate diff for helpful error message
        template_lines = template_normalized.split("\n")
        checked_lines = checked_in_normalized.split("\n")

        error_msg = [
            ".env.example is out of sync with the CLI generator!",
            "",
            "To fix, run:",
            "    uv run minerva init --force",
            "",
            "Then commit the updated .env.example file.",
            "",
            f"Template lines: {len(template_lines)}",
            f"Checked-in lines: {len(checked_lines)}",
        ]

        # Find first difference
        for i, (t_line, c_line) in enumerate(zip(template_lines, checked_lines)):
            if t_line != c_line:
                error_msg.extend(
                    [
                        "",
                        f"First difference at line {i + 1}:",
                        f"  Template: {repr(t_line)}",
                        f"  Checked-in: {repr(c_line)}",
                    ]
                )
                break
        else:
            # Different number of lines
            if len(template_lines) > len(checked_lines):
                error_msg.extend(
                    [
                        "",
                        f"Template has {len(template_lines) - len(checked_lines)} extra lines:",
                        f"  Line {len(checked_lines) + 1}: {repr(template_lines[len(checked_lines)])}",
                    ]
                )
            else:
                error_msg.extend(
                    [
                        "",
                        f"Checked-in file has {len(checked_lines) - len(template_lines)} extra lines",
                    ]
                )

        raise AssertionError("\n".join(error_msg))
